version: '3.7'

# Internal Connections between services
networks:
  basic_network:
    name: basic_network
    driver: bridge
    ipam:
      config:
       - subnet: 10.0.6.0/24

# Services
services:  
  elasticsearch:
    image: elasticsearch:6.4.2
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 9200:9200
    networks:
      - basic_network

  imatch:
    image: dsys/match:latest
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "gunicorn", "-b", "0.0.0.0:8888", "-w", "1", "server:app"]
    ports:
      - 8888:8888
    networks:
      - basic_network
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
