version: '3.7'
x-services-vars: &services-vars
  KAFKA_URL: kafka:9092
  KAFKA_TOPIC: testing
  KAFKA_PARTITIONS: 8 # This should be the same as consumer.MAX_TASKS

x-locale-vars: &locale-vars
  TZ: US/Central
  LANG: en_US.UTF-8
  LANGUAGE: en_US

# Internal Connections between services
networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
       - subnet: 10.0.4.0/24

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka_network
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: kafka
    hostname: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_HOSTNAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_LOG_CLEANER_DELETE_RETENTION_MS=3600000
      - KAFKA_LOG4J_ROOT_LOGLEVEL=WARN
    networks:
      - kafka_network
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper

  # Sending Messages
  producer:
    build: producer/.
    image: producer-image
    container_name: producer
    command: python producer.py
    user: 1000:1000
    restart: on-failure
    volumes:
      - ./producer/logs:/logs/
    environment:
      PYTHONUNBUFFERED: 1
      MAX_WORKERS: 4
      MAX_QUEUE: 2500
      LOGGING_LEVEL: 10 # INFO
      MSG_CREATION_DELAY_MS: 25 # We create 40 per second
      SCREENING_RATE: 500 # items
      # Globals
      <<: *locale-vars
      <<: *services-vars
    networks:
      - kafka_network
    links:
      - kafka
    depends_on:
      - kafka

  # Read Kafka messages
  consumer:
    build: consumer/.
    image: consumer-image
    command: python consumer.py
    user: 1000:1000
    restart: on-failure
    volumes:
      - ./consumer/logs:/logs/
    environment:
      PYTHONUNBUFFERED: 1
      MAX_TASKS: 8
      MAX_QUEUE: 2500
      MSG_PROCESING_DELAY_MS: 250 # (MAX_TASKS * 1000) / MSG_PROCESING_DELAY_MS = msg per seconds
      SLEEP_TIME: 1
      LOGGING_LEVEL: 10 # INFO
      SCREENING_RATE: 100 # items
      # Globals
      <<: *locale-vars
      <<: *services-vars
    networks:
      - kafka_network
    links:
      - kafka
    depends_on:
      - kafka